### ISSUE TITLE
w806 CPU exception

### ISSUE THREAD

**Issue by AndrejChoo** [IOsetting/wm-sdk-w806#12]
Hello, Friends. I tried to connect the fatfs library to the SDHC card via SPI on the w806. My card initialization is going well. And when I try to read one block, I get an error on UART monitor:
CPU Exception : 7r0: 00000000	r1: 001010a9	r2: 00000001	r3: 001000a9	r4: c08ed88e	r5: 7c00befb	r6: b90600bf	r7: a4f30200	r8: 4de428b3	r9: 4c83600a	r10: 4e46aa12	r11: 3384e604	r12: ffffffff	r13: 0000002d	r14: 20001100	r15: 000621ea	epsr: e0000340epc :     4dfa.
My question is: what could be the problem? In which files is CPU exceptions processing located? In which file is the stack fnd heap size specified?
I also tried to write a library to work with HARD I2C. Did you also fail to get the START command on the bus? Is it a hardware problem in the chip?
I will be very grateful for answers to my questions. I would really like to understand the work of this MCU in more detail. 
My email andrejchukov@yandex.ru .

**Comment by IOsetting** [comment]
Sorry I hadn't got time to look into this. This error message is generated by the default exception handler through asm code. Maybe you can take a look at the PR #7, which implements fatfs on sdcard.

I hadn't tried hard i2c, I will refer your question to winnermicro.

**Comment by AndrejChoo** [comment]
Thanks

**Comment by IOsetting** [comment]
Please take a look at this. 
* implementation https://gitee.com/iosetting/wm-sdk-w80x/blob/master/platform/drivers/i2c/wm_i2c.c
* register definitions https://gitee.com/iosetting/wm-sdk-w80x/blob/master/include/wm_regs.h

It's the sdk for w801, they share the same mcu core and same pin definitions

**Comment by XuHg-zjcn** [comment]
CPU exception processing is in file "platform/arch/xt804/bsp/vectors.S" and "platform/arch/xt804/bsp/trap_c.c"
I read the ISA document, the meaning of "CPU Exception : 7" is break-point exception.
because the program pointer was encountered an interrupt instruction, so raised the CPU exception.
`epc:  4dfa` is in sec-boot area, not user code area. maybe you're using function pointer mistake, so jump to that.

**Comment by IOsetting** [comment]
@AndrejChoo 

FYI, the hard I2C has been implemented. 

I will close this. Please open a new one if there are any further issues.
