### ISSUE TITLE
ld: error: no memory region specified for loadable section `.eh_frame_hdr'

### ISSUE THREAD

**Issue by gitmun** [IOsetting/wm-sdk-w806#13]
ok  ... ld: error: no memory region specified for loadable section `.eh_frame_hdr'

text of config ...
`#
 Automatically generated file; DO NOT EDIT.
 WinnerMicro W800 Configuration
#

#
 Firmware Configuration
#
CONFIG_W800_TARGET_NAME="W806"
CONFIG_W800_IMAGE_TYPE=1
CONFIG_W800_IMAGE_HEADER=8010000
CONFIG_W800_RUN_ADDRESS=8010400
CONFIG_W800_UPDATE_ADDRESS=8010000
CONFIG_W800_PRIKEY_SEL=0
CONFIG_W800_IMAGE_SIGNATURE=0
CONFIG_W800_CODE_ENCRYPT=0
CONFIG_W800_SIGN_PUBKEY_SRC=0

#
 Download Configuration
#
CONFIG_W800_DOWNLOAD_PORT="ttyUSB0"
CONFIG_W800_DOWNLOAD_RATE=2000000

#
 Compile Configuration
#
 CONFIG_W800_USE_LIB is not set
 CONFIG_W800_FIRMWARE_DEBUG is not set

#
 Toolchain Configuration
#
CONFIG_W800_TOOLCHAIN_PREFIX="csky-abiv2-linux"
CONFIG_W800_TOOLCHAIN_PATH="/opt/toolchains/csky-linux-gnuabiv2-tools-x86_64-glibc-linux-4.9.56-20210423/bin/"`

**Comment by IOsetting** [comment]
I just noticed that you are using glibc toolchains, w806 sdk hasn't been adapted for it.

So far only 2 set of toolchains have been tested working 
* csky-elfabiv2-tools-[arch]-minilibc
* csky-elf-noneabiv2-tools-[arch]-newlib

**Comment by gitmun** [comment]
Ummm ok my system using glibc

**Comment by IOsetting** [comment]
Close for no further discussion
