### ISSUE TITLE
Windows msys2 $make menuconfig gives Permission denied

### ISSUE THREAD

**Issue by ramymagdy-rm** [IOsetting/wm-sdk-w806#14]
Error:
running msys2 build system gives the following error, while attempting to change toolchain executables path
$ make menuconfig
  make: ./tools/W806/mconfig.sh: Permission denied
  make: *** [tools/W806/rules.mk:141: menuconfig] Error 127

system:
msys2 is running onto windows 11, all necessary packages updated/installed
msys2 (run as admin) did not work

**Comment by ramymagdy-rm** [comment]
reviewing https://github.com/msys2/msys2.github.io/issues/168 the problem may be due to windows antimalware or antivirus

**Comment by IOsetting** [comment]
Please execute `ls -l` under path `wm-sdk-w806/tools/W806/` and post the output content.

I guess the permission of mconfig.sh is incorrect.

**Comment by IOsetting** [comment]
Close for no further discussion
