### ISSUE TITLE
make menuconfig unable to perform delete

### ISSUE THREAD

**Issue by ghost** [IOsetting/wm-sdk-w806#15]
Hi.
I cannot delete the input in the following cases.
![image](https://user-images.githubusercontent.com/37032513/149804647-859f632b-d27b-4d10-983d-0d96635576b0.png)

**Comment by ghost** [comment]
so.
I modified the './tools/W806/.config' file directly, but why can't delete it in mconf?

**Comment by IOsetting** [comment]
What if keep ctrl key pressed when you press backspace key? Some terminals may have this problem.

**Comment by IOsetting** [comment]
Close this issue for no further discussion.
