### ISSUE TITLE
How to make own custom app / Project template

### ISSUE THREAD

**Issue by nyh-workshop** [IOsetting/wm-sdk-w806#22]
Hi there, I managed to compile and flash the W806 kit successfully using the guides provided.

However, I'm not sure which app it uploads to the board. It said "W806.bin" in the "make flash" output - but I couldn't locate that sample app that is associated with the W806.bin. Is it in the "demo" folder, or one of the apps in the "app" folder?

Also, it could be easy if there's an empty project template which I can work on different things. Is it possible to just  reuse that whole "WM-SDK-W806" folder and add my custom app inside (possibly passing a parameter to the make command?), or I have to create another separate copy of "WM-SDK-W806" if I need to have my own app inside?

**Comment by IOsetting** [comment]
For the first question
* The files generated for uploading are under folder *bin/W806* 
* The make compiles the source files under folder *app*
* The make process won't compile the demos, in another word, you can safely remove all folders under *demo* folder (just keep *demo/Makefile*)

For the second question
* This repository is for quick start -- clean the files under *app* and *demo* folder will make it an empty project.
* Yes, you can modify *Makefile*s and the *.mk* files to fit your needs.

**Comment by nyh-workshop** [comment]
Thank you for the assistance. 👍
