### ISSUE TITLE
"Enable Use Lib" does not work correctly in SDK and CDK project.

### ISSUE THREAD

**Issue by nyh-workshop** [IOsetting/wm-sdk-w806#24]
Hello there,
I have just compiled a simple C++14 app with a number of constexpr and static declarations. However, it could not compile with reasons of `undefined reference to __cxa_guard_acquire` in the compilation.

From the [static compilation guides in C++](https://alex-robenko.gitbook.io/bare_metal_cpp/compiler_output/static), it is noticed that some form of stdlib needed to be enabled to be successfully compiled, or disabling the thread safety mechanism. However, since this app will be also used with a FreeRTOS, I will have to use the libc ("Enable Use Lib"?) provided.

After enabling the "Enable Use Lib" in menuconfig, and compiling it, I got a warning:
```
0/../../../../csky-elfabiv2/bin/ld.exe: warning: cannot find entry symbol Reset_Handler; defaulting to 08010400
OBJCOPY  W806.bin
generate normal image completed.
generate normal image completed.
compress binary completed.
generate compressed image completed.
build finished!
connecting serial...
```
and I could not get the program to run, and I'm suspecting it's just waiting for the user to upload binary in the terminal:
`MMMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC`
It is possible too that it's not jumping to the intended program location.

**Comment by nyh-workshop** [comment]
Also on the same issue, I'm not sure how to "Enable Use Lib" in the CDK project - I have added these option USE_LIB=1 in the compilation flags and options but it doesn't work that way.

I have just dug out the SDK from the [official WM site](https://www.winnermicro.com/html/1/156/158/558.html) (check the 软件资料 section, then download **W800 SDK v1.00.08.rar**).

The Makefile for the W800 SDK contains the USE_LIB=1 which this current one doesn't have:
```
ifeq ($(USE_LIB), 1)
LINKLIB += \
	$(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libwmarch$(LIB_EXT)      \
	$(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libwmcommon$(LIB_EXT)    \
	$(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libdrivers$(LIB_EXT)     \
	$(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libnetwork$(LIB_EXT)     \
	$(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libos$(LIB_EXT)          \
	$(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libwmsys$(LIB_EXT)
endif
```

However, the probable reason for the SDK that is not finding the Reset_Handler is the "libwmarch.a" does not exist in this wm-sdk-w806. A "make lib" would solve this issue, however the Makefile should be accomodated for USE_LIB=1 to include these included generated libraries in the /lib/W806.

**Comment by IOsetting** [comment]
You are right. The `LINKLIB` in Makefile should include extra targets to fix the link error.
```
LINKLIB =     \
    $(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libdsp$(LIB_EXT)
ifeq ($(USE_LIB), 1)
LINKLIB +=    \
    $(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libwmarch$(LIB_EXT)    \
    $(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libwmcomponent$(LIB_EXT)    \
    $(TOP_DIR)/lib/$(CONFIG_ARCH_TYPE)/libdrivers$(LIB_EXT)
endif
```
