### ISSUE TITLE
enable signature and privkey load

### ISSUE THREAD

**Issue by arunmagesh** [IOsetting/wm-sdk-w806#26]
I am trying to enable firmware signature but it just doesn't work. 

I first enabled image key select with/without signature. the code just works irrespective of anything. 

I dont see any way to flash the otp or something to load the priv key inside.

**Comment by IOsetting** [comment]
Hi Arun,
If you mean the firmware encryption, please refer to this document http://ask.winnermicro.com/article/75.html (can be translated in Chrome) and the tool can be downloaded from [this link](http://cloud.winnermicro.com/d/5da225c7add24433b00b/?p=%2FW80X%2FW80X%E8%8A%AF%E7%89%87%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7%2F%E5%9B%BA%E4%BB%B6%E9%98%B2%E6%8B%B7%E8%B4%9D&mode=list).
I didn't use this feature so I am not quite sure this will help.

**Comment by arunmagesh** [comment]
back again! the tool just fails to open even with every possible configuration. Did you by anychance got a look at the firmware signing?
