### ISSUE TITLE
libc_port.c caused compiler error

### ISSUE THREAD

**Issue by allankliu** [IOsetting/wm-sdk-w806#27]
PS: I have read through your closed issue for libc_port.c. And I can not see the final conclusion and solution for that. So I re-open the issue.

I following the instruction on [your CSDN page](https://blog.csdn.net/michaelchain/article/details/121253966), with only exepctions, that I downloaded the toolchain from the  [WM website.](http://82.157.145.101/download/toolkits/winnermicro/w806/)

I repeated my procedure three times on:
- Alicloud ECS with Ubuntu 16.04 x86_64 (amd64)
- Ubuntu Kylin 20.04 x86_64 (amd64)
- WSL1 Ubuntu 18.04 x86_64

I tried to build wm-sdk-w806/wm-sdk-w80x. The strange things are: 
- AliCloud Ubuntu, w806 [Y]/w80x [Y]
- Kylin Ubuntu, w806 [N]/w80x [Y]
- WSL1 Ubuntu, w806 [N]/w80x [Y]
 
I installed csky-elfabiv2-tools-x86_64-minilibc-20210423.tar.gz toolchain and cloned the source from Github into a Ubuntu in ECS. I can make all successfully and it also works fine for wm-sdk-w80x. 

However when I repeat the procedure on Kylin Ubuntu 20.04 64bit version in my desktop, I got a compilation error as following:

```
$ make all
......
AR       libwmbsp.a
/opt/toolchains/csky-elfabiv2-tools-x86_64-minilibc-20210423/bin/csky-abiv2-elf-ar: creating ../../../../bin/build/W806/lib/libwmbsp.a
make[3]: Leaving directory '/home/allankliu/wm-sdk-w806/platform/arch/xt804/bsp'
make[3]: Entering directory '/home/allankliu/wm-sdk-w806/platform/arch/xt804/libc'
CC       libc_port.c
libc_port.c: In function ‘_ftoa’:
libc_port.c:888:3: internal compiler error: Illegal instruction
   if (diff > 0.5) {
   ^~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
../../../../tools/W806/rules.mk:183: recipe for target '../../../../bin/build/W806/obj/platform/arch/xt804/libc/libc_port.o' failed
make[3]: *** [../../../../bin/build/W806/obj/platform/arch/xt804/libc/libc_port.o] Error 1
make[3]: Leaving directory '/home/allankliu/wm-sdk-w806/platform/arch/xt804/libc'
../../../tools/W806/rules.mk:170: recipe for target '.subdirs' failed
make[2]: *** [.subdirs] Error 2
make[2]: Leaving directory '/home/allankliu/wm-sdk-w806/platform/arch/xt804'
../../tools/W806/rules.mk:170: recipe for target '.subdirs' failed
make[1]: *** [.subdirs] Error 2
make[1]: Leaving directory '/home/allankliu/wm-sdk-w806/platform/arch'
tools/W806/rules.mk:170: recipe for target '.subdirs' failed
make: *** [.subdirs] Error 2
```

But building for wm-sdk-w80x works fine. I compared the sources between ECS/Desktop, the csky tools are identical, the sources are identical. But only building for wm-sdk-w806 will throw such error in my desktop. And it will throw the error in some other local machines. I git pull the source, I changed the source...... I didn't get any clue. So far I have to build the source in the ECS anyway.

The good news is that I have both working and non-working samples at hand. The bad news is that I can not find the clue.

**Comment by allankliu** [comment]
I suspect that toolchain aka csky-elfabiv2-gcc is using some features which old CPU doesn't have. That means we have to dive into  the cross-toolchain source code. I am using WSL1/Ubuntu and Kylin/Ubuntu on same old physical Pentium 4 PC because I want to use it as part of my compiling pool. Both failed. Then I switch to a i5 PC. Kylin/Ubuntu works fine with the source and toolchain.

So the error maybe related to the toolchain indeed.

**Comment by IOsetting** [comment]
This had been reported #17, it is quite weird but I had no clue what is the cause. Thanks for the investigation, this may explain why compiler halts there.

**Comment by allankliu** [comment]
I tried the elder csky toolchain from https://gitee.com/swxu/csky-elfabiv2-tools. Downgrade the cross-compiler from 20210423 to 20200502, then the compiler internal error is disappear.

Since it has a workaround solution, I am going to close the issue. And I attach my PC detail for your reference, just in case if you are interested to find the root cause.

···
systeminfo
[01]: Intel64 Family 6 Model 23 Stepping 10 GenuineIntel ~2936 Mhz
···

compiler internal error with csky-elfabiv2-tools-x86_64-minilibc-20210423.tar.gz
compiler working with csky-elfabiv2-tools-x86_64-minilibc-20200502.tar.gz

**Comment by IOsetting** [comment]
I have raised a ticket on t-head.cn, hopefully they will figure out something to solve it.
