### ISSUE TITLE
硬件SPI ST7567那部分，为何显示不全？

### ISSUE THREAD

**Issue by ohmytime** [IOsetting/wm-sdk-w806#28]
看起来只有上面一点能显示出来想要的字符
下图是我用Fill(1)的结果
![image](https://user-images.githubusercontent.com/490477/218393563-319d2be4-e3f8-43d7-bd7d-1bf688941564.png)

**Comment by ohmytime** [comment]
问题出在了偏移量上吗？我的也是ST7567

**Comment by ohmytime** [comment]
确切来说，只显示了上面8行，下面的都没显示。

**Comment by IOsetting** [comment]
I met this problem before, some ST7567 doesn't support row/page shift, so the following code might not work
```c
void ST7567_UpdateScreen(void) 
{
    ST7567_WriteCommand(ST7567_SET_PAGE_ADDRESS | (0x00 & ST7567_SET_PAGE_ADDRESS_MASK));
    ST7567_WriteCommand(ST7567_SET_COLUMN_ADDRESS_MSB);
    ST7567_WriteCommand(ST7567_SET_COLUMN_ADDRESS_LSB);
    ST7567_Transmit(ST7567_Buffer_all, sizeof(ST7567_Buffer_all), ST7567_TIMEOUT);
}
```
You need to update it page by page like this. The following code might not work out-of-box, just for your reference.
```c
void ST7567_UpdateScreen(void) 
{
    uint8_t i = 0, *pt = ST7567_Buffer_all;
    for (i = 0; i < ST7567_PAGES; i++)
    {
        ST7567_WriteCommand(ST7567_SET_PAGE_ADDRESS|(i & ST7567_SET_PAGE_ADDRESS_MASK));
        ST7567_WriteCommand(ST7567_SET_COLUMN_ADDRESS_MSB|(ST7567_X_OFFSET >> 4));
        ST7567_WriteCommand(ST7567_SET_COLUMN_ADDRESS_LSB|(ST7567_X_OFFSET & 0x0F));
        ST7567_Transmit(pt + (ST7567_WIDTH * i), ST7567_WIDTH, ST7567_TIMEOUT);
    }
}
```

**Comment by ohmytime** [comment]
Thank you for your Tips ~

After I use your reference code, the screen can be fully displayed, but a new problem has appeared,
It seems to be displayed a bit misplaced.
![image](https://user-images.githubusercontent.com/490477/218406326-54c81f72-33a6-433d-bcf1-1cadd2398fb9.png)

**Comment by IOsetting** [comment]
Adjust the following configurations, depends on your hardware and display mode
```c
// Additional bytes in each row
#define ST7567_SEG_EXPAND 4
// X orientation
#define ST7567_X_ORIENT ST7567_SEG_DIRECTION_REVERSE
// Y orientation
#define ST7567_Y_ORIENT ST7567_COM_DIRECTION_NORMAL
```
and
```c
#if ST7567_X_ORIENT == ST7567_SEG_DIRECTION_REVERSE
    #define ST7567_X_OFFSET  ST7567_SEG_EXPAND
#else
    #define ST7567_X_OFFSET  0
#endif
```

**Comment by ohmytime** [comment]
> Adjust the following configurations, depends on your hardware and display mode
> 
> ```c
> // Additional bytes in each row
> #define ST7567_SEG_EXPAND 4
> // X orientation
> #define ST7567_X_ORIENT ST7567_SEG_DIRECTION_REVERSE
> // Y orientation
> #define ST7567_Y_ORIENT ST7567_COM_DIRECTION_NORMAL
> ```
> 
> and
> 
> ```c
> #if ST7567_X_ORIENT == ST7567_SEG_DIRECTION_REVERSE
>     #define ST7567_X_OFFSET  ST7567_SEG_EXPAND
> #else
>     #define ST7567_X_OFFSET  0
> #endif
> ```

Thank you so much for your fast reply, I will try.

**Comment by ohmytime** [comment]
I change it to this,finally it works.

```C
// Additional bytes in each row
#define ST7567_SEG_EXPAND 0
// X orientation
#define ST7567_X_ORIENT ST7567_SEG_DIRECTION_NORMAL
// Y orientation
// #define ST7567_Y_ORIENT ST7567_COM_DIRECTION_NORMAL
#define ST7567_Y_ORIENT ST7567_COM_DIRECTION_REVERSE

```

**Comment by IOsetting** [comment]
Cool!

**Comment by ohmytime** [comment]
Thanks a lot for your open source library,
it's very cool !

**Comment by IOsetting** [comment]
You are welcome.
