### ISSUE TITLE
macOS flash tool

### ISSUE THREAD

**Issue by KenjutsuGH** [IOsetting/wm-sdk-w806#30]
Is there a flash tool available for macOS?

**Comment by crosstyan** [comment]
You could find the source code of [wm_tool.c](https://github.com/IOsetting/wm-sdk-w806/blob/main/tools/W806/wm_tool.c) in the SDK. Building it is trivial since no other dependency is needed.

```bash
 gcc  -O2 -lpthread  -o wm_tool wm_tool.c
```

**Comment by KenjutsuGH** [comment]
Thank you, it compiles without errors
