### ISSUE TITLE
按reset不刷机

### ISSUE THREAD

**Issue by scroot** [IOsetting/wm-sdk-w806#6]
按了reset没反应，怎么回事

**Comment by IOsetting** [comment]
* W806还是W801? 
* Windows还是Linux? 
* USB端口填写是否正确? Windows下应该是COM3, COM4这些, Linux下是ttyUSB0, ttyUSB1这些
* 按住BOOT后按RESET强制重启能进入下载状态么?

**Comment by IOsetting** [comment]
Closed due to inactivity, feel free to open another ticket if the problem persists.
